#!/bin/bash

echo "🔑 CONFIGURING AI API KEYS IN RENDER"
echo "===================================="
echo ""
echo "To enable REAL AI in production, add these environment variables in Render:"
echo ""
echo "1. Go to: https://dashboard.render.com/services"
echo "2. Click on 'brainops-backend-prod'"
echo "3. Go to 'Environment' tab"
echo "4. Add these variables:"
echo ""
echo "OPENAI_API_KEY=sk-..."
echo "ANTHROPIC_API_KEY=sk-ant-..."
echo "GEMINI_API_KEY=AIza..."
echo ""
echo "Without these keys, the system falls back to intelligent rule-based AI."
echo ""
echo "Current Status:"
echo "- ✅ Real AI integration code deployed (v9.40)"
echo "- ✅ Multi-provider fallback system active"
echo "- ⚠️  API keys not configured in production"
echo "- ⚠️  All endpoints returning 500 errors"
echo ""
echo "Once keys are added:"
echo "1. The service will automatically restart"
echo "2. AI endpoints will use real AI providers"
echo "3. Run test_real_ai_endpoints.py to verify"
echo ""
echo "Provider Documentation:"
echo "- OpenAI: https://platform.openai.com/api-keys"
echo "- Anthropic: https://console.anthropic.com/settings/keys"
echo "- Google AI: https://makersuite.google.com/app/apikey"