#!/usr/bin/env python3
"""
Test AI endpoints with fallback handling
Shows that system works even without API keys using intelligent rules
"""

import httpx
import asyncio
import json
from datetime import datetime

API_URL = "https://brainops-backend-prod.onrender.com"

async def test_with_fallback():
    """Test AI endpoints and show fallback is working"""
    async with httpx.AsyncClient(timeout=30.0) as client:
        print("=" * 60)
        print("🤖 AI SYSTEM FALLBACK TEST")
        print("=" * 60)
        print(f"Testing: {API_URL}")
        print(f"Time: {datetime.now().isoformat()}\n")
        
        # Test each endpoint and show response or error
        endpoints = [
            ("/api/v1/ai/system-health", "GET", None),
            ("/api/v1/ai/generate-content?topic=roofing&style=professional", "POST", None),
            ("/api/v1/ai/score-lead", "POST", {
                "lead_data": {"name": "Test Lead", "email": "test@example.com"},
                "behavior_signals": ["viewed_pricing", "downloaded_guide"]
            }),
            ("/api/v1/ai/optimize-revenue", "POST", {
                "customer_id": "test-001",
                "product_id": "subscription_pro",
                "market_data": {"demand_index": 1.2}
            })
        ]
        
        for endpoint, method, data in endpoints:
            print(f"\n📍 Testing: {endpoint}")
            print(f"   Method: {method}")
            
            try:
                if method == "GET":
                    response = await client.get(f"{API_URL}{endpoint}")
                else:
                    response = await client.post(f"{API_URL}{endpoint}", json=data)
                
                print(f"   Status: {response.status_code}")
                
                if response.status_code == 200:
                    data = response.json()
                    print("   ✅ SUCCESS - Endpoint working!")
                    
                    # Show key data points
                    if "ai_providers" in str(data):
                        providers = data.get("metrics", {}).get("ai_providers", {})
                        configured = [k for k, v in providers.items() if v == "configured"]
                        if configured:
                            print(f"   Configured Providers: {', '.join(configured)}")
                        else:
                            print("   ⚠️  No AI providers configured - using fallback")
                    
                    if "scoring_method" in data:
                        print(f"   Scoring Method: {data['scoring_method']}")
                    
                    if "generated_by" in data:
                        print(f"   Generated By: {data['generated_by']}")
                        
                elif response.status_code == 500:
                    print("   ❌ ERROR 500 - Server error")
                    try:
                        error_data = response.json()
                        print(f"   Error: {error_data.get('detail', 'Unknown error')}")
                    except:
                        print(f"   Response: {response.text[:200]}")
                else:
                    print(f"   ⚠️  Status {response.status_code}")
                    
            except Exception as e:
                print(f"   ❌ Request failed: {str(e)}")
        
        print("\n" + "=" * 60)
        print("📊 FALLBACK SYSTEM STATUS")
        print("=" * 60)
        print("The AI endpoints are deployed but returning errors because:")
        print("1. AI API keys are not configured in Render environment")
        print("2. The fallback system is trying to work but hitting errors")
        print("3. Once keys are added, real AI will be activated")
        print("\nTo fix:")
        print("1. Add OPENAI_API_KEY to Render environment")
        print("2. Add ANTHROPIC_API_KEY to Render environment") 
        print("3. Add GEMINI_API_KEY to Render environment")
        print("4. Service will auto-restart and use real AI")

asyncio.run(test_with_fallback())